### ISSUE TITLE
get_pear_module_info is broken on modern systems (maybe everywhere)

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/php-pear#1]
This line results in a blank pear command ($c is empty), so it ends up running the GNU info command instead of "pear info".

```
local ($c) = grep { $_->[1] eq $pver } &get_pear_commands();
```

https://github.com/virtualmin/php-pear/blob/master/php-pear-lib.pl#L171

I'm not sure what's trying to happen there...looks like it's picking the command based on a PHP/Pear version, but the end result is that even though pear is configured, it doesn't end up in $c.

I'm guessing that means all of the calls to get_pear_commands will fail (install_pear_module, uninstall_pear_modules, and get_pear_module_info all have this usage).

This happens on all of my CentOS 7 systems, and a Fedora 23 system. I don't have anything else handy to test on, to now if it effects others. These systems have a variety of PHP versions; Virtualmin.com, in particular has multiple PHP versions installed from third party sources, while the others have stock PHP, but C7 and Fedora 23 have very different PHP versions. But, all behave badly (Fedora acts differently, in that it seems to run nothing, rather than running info...but, we can tackle one problem at a time).

**Comment by jcameron** [comment]
Looks like this case is never expected to happen - a pear command should always be found for the PHP version. I've checked in a change that should reveal which version is missing.

**Comment by swelljoe** [comment]
OK, actually, now I see there are multiple things going on. One is that all of my other systems have the non-version aware php-pear module (somewhat non-version aware, anyway; it's what's in the 1.5 branch in the old repo); so what I thought was happening is a little different from what is actually happening.

Regardless, the version of php-pear in the repos for users is not working for installations and info on CentOS 7, and probably not on other systems either. Looks like we need to roll a new php-pear module. Is what's in this repo suitable for a release? If so, I'll do a strict/warn pass on it, test it a bit more, and tag a 1.6 release and package it up.

**Comment by jcameron** [comment]
I just tested the latest code on a CentOS 7 system, and it worked fine.

Is the pear command just called `pear` on your box?

**Comment by swelljoe** [comment]
Yes; my problem on CentOS 7 was that it was running version 1.5, which is broken (maybe everywhere, maybe just on C7/Fedora). What's in git right now actually works fine (with or without this patch). I didn't notice it had changed since the last release.

But, the version we're currently shipping does not work (at least on CentOS 7), no matter what version of PHP is installed. Pear is installed, and is detected correctly for some actions (it works to list packages) but not to install or get info on a package. In short: We just need to roll a 1.6. I'm happy to do that unless you tell me there's something broken about this version that I haven't noticed. I probably need to test it on a system with multiple PHP versions, though I don't necessarily understand how that's supposed to work in order to test it effectively...it looks like multi-php support is still kinda incomplete here. But, even if it only works with one PHP version, that's better than not working, at all, which is what we're currently shipping.

**Comment by swelljoe** [comment]
And, yes, there is a pear command at /usr/bin/pear on all of the effected boxes (even if, in one case, there's also another pear for php 5.6).

**Comment by jcameron** [comment]
Ok, I've bumped to version up to 1.6 - there's no reason not to roll that out right now.

**Comment by swelljoe** [comment]
Cool. Will do.

**Comment by swelljoe** [comment]
Hmmm...not seeing a check-in that changes version. I pushed a strict/warn update a few minutes ago, maybe you're just sorting out the unexpected needed merge? I can bump that rev and such, if you're busy.

**Comment by jcameron** [comment]
I tried to push, but got the error 

`ERROR: Permission to virtualmin/php-pear.git denied to webmin.
fatal: The remote end hung up unexpectedly`

**Comment by swelljoe** [comment]
You'll need to accept the invitation to participate as the webmin user (or commit as jcameron). I see you've accepted as jcameron, but your webmin user hasn't confirmed.

**Comment by jcameron** [comment]
Thanks, that worked.

I have no idea how to select which account I am logging into github with though! The `git config --list` command shows that my email is `jcameron@webmin.com`

**Comment by swelljoe** [comment]
I know it relies on public key and not user name, but I don't really grok it either, but I found this:http://stackoverflow.com/questions/7927750/specify-an-ssh-key-for-git-push-for-a-given-domain

So, there's a variety of ways to force it to commit with a specific key. But, I'll make sure both of your accounts are invited to every repo I create during this process. Now that you know you have to confirm it, it should be fine, however you want to commit.
